### PR TITLE
Add Windows Apache Support

### PR DESCRIPTION
**Pull request by embedvr**
This should add support for restarting if you're running Apache on Windows. I don't even know if this works on python windows, but whatever.

### CODE REVIEW

**Comment by onyxcode** [comment]
@creepinson Mind helping me take a look at this?

**Comment by onyxcode** [comment]
@embedvr This looks great! If you could just make sure the spelling is correct on the install instructions, I'll merge the PR immediately.

**Comment by creepinson** [comment]
Again, you used the wrong file in the commits. Its the gen/apache not start.py. I am going to remove it soon so you dont need to deal with it again lol.

**Comment by onyxcode** [comment]
> Looks good, although you used the wrong file in the commits. Its the gen/apache not start.py. I am going to remove it soon so you dont need to deal with it again lol.

Ah yes, I forgot about that. I'm not used to packages just yet lol

**Comment by creepinson** [comment]
Also, I don't know if a2enmod works on windows so this might not be possible to fix. I use a2enmod to enable the proxy mod automatically in the apache.py file.

**Comment by creepinson** [comment]
Closed #6

**Pull request closed without merging**
